### PR TITLE
Initial setup

### PR DESCRIPTION
**Pull request by vaibhav-mahalle**
- Initial setup
- Basic Pages and routing
- Favicon

### CODE REVIEW

**Review by nishasen — APPROVED** [review]
You can delete the redundant files from public folder. PageNotFound file is being created inside archive file, do check it once.

**Review by nakulsharma15 — APPROVED** [review]
Everything Looks Good. No changes suggested

**Review by RahulSingh9131 — APPROVED** [review]
Approving your initial setup. 
suggestion- add a user other than adarsh balika😄

**Comment by vaibhav-mahalle** [comment]
>

**Pull request merged**
